### ISSUE TITLE
Error handling not functional

### ISSUE THREAD

**Issue by bmherold** [angular-tools/ng-jsoneditor#2]
Providing an options.error callback does not seem to work. A workaround so far has been to hook error checking onto the ace editor with `ng-jsoneditor="editorLoaded"`. But if I switch modes to tree and then back, it's gone since editorLoaded only fires the first time. Any thoughts?

   
    $scope.editorLoaded = function(jsonEditor) {
      console.log('[json editor loaded]');
      $scope.editor.instance = jsonEditor;
    
      //TODO: we have a problem, this only fires once, so the error handler only gets attached the first time :(
      $timeout(function() {
        if ($scope.editor.options.mode === 'code') {
          _initErrorHandler(jsonEditor);
        }
      });
    };

    var _initErrorHandler = function(jsonEditor) {
      console.log('======= initializing error handler ===');
      jsonEditor.editor.getSession().on('change', function() {
        var debounce;
        $timeout.cancel(debounce);
        debounce = $timeout(function() {
          return $scope.$apply(function() {
            try {
              jsonEditor.get();
              console.log('jsonEditor', 'no errors in edited content');
              $scope.error = false;
            } catch (_error) {
              console.log('jsonEditor', 'editor contents not valid json');
              $scope.error = _error;
            }
          });
        }, 300);
      });
    }

**Comment by angular-tools** [comment]
Hi,

Sorry for not able to reply earlier.

I'm not sure why the error handler isn't working because `ng-jsoneditor` is only a wrapper on the jsoneditor component and the only function it override is the `change` function.

Rest all the `options` are passed as-is to when the editor is created.

How are you using it in your code? Would it be possible for you to create a `plunkr` or `jsfiddle` for it to show the error?

Thanks.
